{{- if and .Values.serviceAccount.create .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kustomize-mutating-webhook.fullname" . }}
  labels:
    {{- include "kustomize-mutating-webhook.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - kustomize.toolkit.fluxcd.io
    resources:
      - kustomizations
    verbs:
      - get
      - list
      - watch
      - patch
{{- end }}
