{{- if .Values.networkpolicy.create -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kustomize-mutating-webhook.fullname" . }}
  labels:
    {{- include "kustomize-mutating-webhook.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kustomize-mutating-webhook.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow inbound traffic on the webhook port from any source
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
  egress:
    - ports:
        - port: 443
          protocol: TCP
        - port: 6443
          protocol: TCP
      to:
        - ipBlock:
            cidr: 0.0.0.0/0
{{- end }}
