



{{- if .Values.certManager.enabled -}}
{{- if not .Values.certManager.CASClusterIssuer.enabled -}}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kustomize-mutating-webhook.fullname" . }}
  labels:
    {{- include "kustomize-mutating-webhook.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kustomize-mutating-webhook.fullname" . }}
  labels:
    {{- include "kustomize-mutating-webhook.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "kustomize-mutating-webhook.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "kustomize-mutating-webhook.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  {{- if .Values.certManager.CASClusterIssuer.enabled }}
  issuerRef:
    group: {{ .Values.certManager.CASClusterIssuer.group }}
    kind: {{ .Values.certManager.CASClusterIssuer.kind }}
    name: {{ .Values.certManager.CASClusterIssuer.name }}
  {{- else }}
  issuerRef:
    name: {{ include "kustomize-mutating-webhook.fullname" . }}
    kind: Issuer
  {{- end }}
  secretName: {{ include "kustomize-mutating-webhook.fullname" . }}-tls
  duration: {{ .Values.certManager.certificateDuration | default "2160h" }}
  renewBefore: {{ .Values.certManager.certificateRenewBefore | default "360h" }}
{{- end }}
